### ISSUE TITLE
IoT Central support for Microsoft Modbus desired properties

### ISSUE THREAD

**Issue by sandervandevelde** [iot-for-all/awesome-iotcentral#2]
Hello,

I have set up an IoT Edge device connected to IoT Central. One of the modules connected is a Microsoft Modbus device (taken from the marketplace).

These are the initial Modbus module desired properties:

```
        "Modbus": {
            "properties.desired": {
                "PublishInterval": 100,
                "SlaveConfigs": {
                    "Slave01": {
                        "SlaveConnection": "192.168.43.232",
                        "HwId": "Wise01",
                        "Operations": {
                            "Op01": {
                                "PollingInterval": "100",
                                "UnitId": "1",
                                "StartAddress": "00131",
                                "Count": "1",
                                "DisplayName": "IFM00"
                            }
                        }
                    }
                }
            }
        },
```

If I import the deployment manifest, the import succeeds:

![image](https://user-images.githubusercontent.com/694737/103095770-16b87b80-4602-11eb-93e9-57c7967ea7f8.png)

I do not change anything to the interface afterward.

Also, the deployment and the first connected device perform well. Here is the Manage page:

![image](https://user-images.githubusercontent.com/694737/103095887-757df500-4602-11eb-9d0b-0cf6058bd43e.png)

But, when I want to change the IP address in the IoT Central portal, the Modbus module desired properties update fails:

![image](https://user-images.githubusercontent.com/694737/103095994-be35ae00-4602-11eb-8803-182f508e6872.png)

It seems the desired properties sent are not matching that what the code is expecting.

Can you confirm this behavior? Is there a workaround?

**Comment by sseiber** [comment]
@sandervandevelde - can you share the model you are using in IoT Central. It appears that it does not match the desired properties you have listed above.
