### ISSUE TITLE
Adding tags for devices in Azure IOT Central

### ISSUE THREAD

**Issue by Dewk0287** [iot-for-all/awesome-iotcentral#5]
How can we add tags for device in Azure IOT Central. Below are the examples for same.

"tags": {
        "mappings": [
            {
                "a": "fdsa",
                "b": {
                    "c": "fdsa",
                    "d": "fdas",
                    "e": "fdas",
                    "f": "fdasfas",
                    "g": "asdfasdsafdsa"
                }
            },
           
{
                "a": "fdsa",
                "b": {
                    "c": "fdsa",
                    "d": "fdas",
                    "e": "fdas",
                    "f": "fdasfas",
                    "g": "asdfasdsafdsa"
                }
            },

            
{
                "a": "fdsa",
                "b": {
                    "c": "fdsa",
                    "d": "fdas",
                    "e": "fdas",
                    "f": "fdasfas",
                    "g": "asdfasdsafdsa"
                }
            },

        ]
    },

**Comment by kimwolk** [comment]
Use Map as your Schema type.  Define key name and string value pair in the model.  You can add a as many key instances on the device instance.

Formal definition:  https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/dtdlv2.md#map.

Example model:

{
    "@id": "dtmi:custom2cd9jfvmfru:abc3ep;1",
    "@type": "Interface",
    "contents": [
        {
            "@id": "dtmi:custom2cd9jfvmfru:abc3ep:MapExample;1",
            "@type": "Property",
            "displayName": {
                "en": "Map Example"
            },
            "name": "MapExample",
            "schema": {
                "@id": "dtmi:custom2cd9jfvmfru:abc3ep:MapExample:schema;1",
                "@type": "Map",
                "displayName": {
                    "en": "Map"
                },
                "mapKey": {
                    "@id": "dtmi:custom2cd9jfvmfru:abc3ep:MapExample:schema:mapKey:keyName;1",
                    "displayName": {
                        "en": "keyName"
                    },
                    "name": "keyName",
                    "schema": "string"
                },
                "mapValue": {
                    "@id": "dtmi:custom2cd9jfvmfru:abc3ep:MapExample:schema:mapValue:keyValue;1",
                    "displayName": {
                        "en": "keyValue"
                    },
                    "name": "keyValue",
                    "schema": "string"
                }
            }
        }
    ],
    "displayName": {
        "en": "abc"
    },
    "@context": [
        "dtmi:iotcentral:context;2",
        "dtmi:dtdl:context;2"
    ]
}

**Comment by Dewk0287** [comment]
Thanks! is it possible to add custom properties to each device independently not to the whole template?

**Comment by kimwolk** [comment]
No.  This is not possible currently.  We are looking at making this easier to do.
